services:
  api:
    build:
      context: .
      target: development
    container_name: api
    working_dir: /app
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/techchallenge
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL:-admin@local.dev}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
      - SEED_ADMIN_NAME=${SEED_ADMIN_NAME:-Admin local}
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techchallenge
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d techchallenge']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgresdata:
