apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tech-challenge-namespace
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: tech-challenge-pos-fiap
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
