apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: tech-challenge-namespace
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: tech-challenge-pos-fiap
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/techchallenge
  JWT_SECRET: altere-este-segredo
  SEED_ADMIN_PASSWORD: admin123
